language: rust
rust:
- nightly
addons:
  ssh_known_hosts: 37.139.22.109

before_install:
  - openssl aes-256-cbc -K $encrypted_4ed4cdc9df6d_key -iv $encrypted_4ed4cdc9df6d_iv
    -in etc/deploy_key.enc -out etc/deploy_key -d

after_success:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy_key
- ssh-add .travis/deploy_key
- git remote add deploy dokku@37.139.22.109:clippy
- git push -u deploy master
